spring:
  application:
    name: eureka
server:
  port: 2001
eureka:
  server:
    enable-self-preservation: false #关闭保护模式
  instance:
    hostname: eureka1 # 集群中用hostname来区分服务器
    prefer-ip-address: true #注册ip，不注册主机名
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 界面列表中显示的格式也显示ip
  client:
    register-with-eureka: false # 单台服务器不向自己注册
    fetch-registry: false # 单台服务器不从自己拉取
